task: detection

num_classes: 10
remap_mscoco_category: True

train_dataloader: # COCO style
  type: DataLoader
  dataset: 
    type: CocoDetection
    # img_folder: /Dataset/EvDET200K/event_frame/train # Change it to your data address
    # ann_file: /Dataset/EvDET200K/event_frame/annotation/train.json # Change it to your label address   
    img_folder: /media/amax/c08a625b-023d-436f-b33e-9652dc1bc7c01/DATA/dataset/ESO/coco_style/data/
    ann_file: /media/amax/c08a625b-023d-436f-b33e-9652dc1bc7c01/DATA/dataset/ESO/coco_style/annotations/train_sg.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: ~
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    # img_folder: /Dataset/EvDET200K/event_frame/test # Change it to your data address
    # ann_file: /Dataset/EvDET200K/event_frame/annotation/test.json # Change it to your label address
    img_folder: /media/amax/c08a625b-023d-436f-b33e-9652dc1bc7c01/DATA/dataset/ESO/coco_style/data/
    ann_file: /media/amax/c08a625b-023d-436f-b33e-9652dc1bc7c01/DATA/dataset/ESO/coco_style/annotations/test_sg.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: ~
  num_workers: 4
  drop_last: False